import { useState, useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, CreditCard, Upload } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { InvoiceProofUpload } from "@/components/billing/InvoiceProofUpload";
import { useAuth } from "@/hooks/useAuth";

interface SubscriptionPlan {
  id: string;
  plan_name: string;
  price: number;
  max_projects: number;
  max_subscribers: number;
}

interface PaymentMethod {
  id: string;
  method_name: string;
  method_type: string;
  details: Record<string, string>;
  instructions: string | null;
}

interface UpgradePlanDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selectedPlan: SubscriptionPlan | null;
  subscriptionId: string | null;
  onSuccess: () => void;
}

export function UpgradePlanDialog({
  open,
  onOpenChange,
  selectedPlan,
  subscriptionId,
  onSuccess,
}: UpgradePlanDialogProps) {
  const { user } = useAuth();
  const [step, setStep] = useState<"info" | "payment" | "upload">("info");
  const [loading, setLoading] = useState(false);
  const [platformMethods, setPlatformMethods] = useState<PaymentMethod[]>([]);
  const [createdInvoiceId, setCreatedInvoiceId] = useState<string | null>(null);

  useEffect(() => {
    if (open) {
      setStep("info");
      setCreatedInvoiceId(null);
      fetchPlatformMethods();
    }
  }, [open]);

  const fetchPlatformMethods = async () => {
    try {
      const { data } = await supabase
        .from("platform_payment_methods")
        .select("*")
        .eq("is_active", true)
        .order("display_order", { ascending: true });

      setPlatformMethods((data || []) as PaymentMethod[]);
    } catch (error) {
      console.error("Failed to fetch platform methods:", error);
    }
  };

  const handleProceedToPayment = async () => {
    if (!user || !selectedPlan) return;

    setLoading(true);
    try {
      // Create invoice - invoice_number is auto-generated by trigger
      const { data: invoice, error } = await supabase
        .from("invoices")
        .insert({
          client_id: user.id,
          subscription_id: subscriptionId,
          plan_id: selectedPlan.id,
          amount: selectedPlan.price,
          status: "pending",
          invoice_number: `INV-${Date.now()}`, // Temporary, will be replaced by trigger
          due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        })
        .select("id")
        .single();

      if (error) throw error;

      setCreatedInvoiceId(invoice.id);
      setStep("payment");
    } catch (error: any) {
      toast.error("Failed to create invoice", { description: error.message });
    } finally {
      setLoading(false);
    }
  };

  const handleUploadComplete = async (url: string) => {
    if (!createdInvoiceId) return;

    try {
      const { error } = await supabase
        .from("invoices")
        .update({
          payment_proof_url: url,
          notes: "Payment proof uploaded, awaiting review",
        })
        .eq("id", createdInvoiceId);

      if (error) throw error;

      toast.success("Payment submitted! We'll review and activate your plan shortly.");
      onOpenChange(false);
      onSuccess();
    } catch (error: any) {
      toast.error("Failed to submit payment", { description: error.message });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>
            {step === "info" && "Upgrade to " + (selectedPlan?.plan_name || "")}
            {step === "payment" && "Complete Payment"}
            {step === "upload" && "Upload Payment Proof"}
          </DialogTitle>
          <DialogDescription>
            {step === "info" && "Review your plan details before proceeding."}
            {step === "payment" && "Send payment using one of the methods below."}
            {step === "upload" && "Upload a screenshot of your payment confirmation."}
          </DialogDescription>
        </DialogHeader>

        {step === "info" && selectedPlan && (
          <div className="space-y-4">
            <div className="bg-muted/30 rounded-lg p-4 space-y-2">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Plan</span>
                <span className="font-medium">{selectedPlan.plan_name}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Price</span>
                <span className="font-medium">${selectedPlan.price}/month</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Projects</span>
                <span className="font-medium">
                  {selectedPlan.max_projects < 0 ? "Unlimited" : selectedPlan.max_projects}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Subscribers</span>
                <span className="font-medium">
                  {selectedPlan.max_subscribers < 0
                    ? "Unlimited"
                    : selectedPlan.max_subscribers.toLocaleString()}
                </span>
              </div>
            </div>
          </div>
        )}

        {step === "payment" && (
          <div className="space-y-4">
            <div className="flex justify-between items-center bg-primary/10 rounded-lg p-3">
              <span>Amount Due</span>
              <Badge variant="default" className="text-lg">
                ${selectedPlan?.price.toFixed(2)}
              </Badge>
            </div>

            {platformMethods.length === 0 ? (
              <p className="text-muted-foreground text-sm text-center py-4">
                No payment methods available. Please contact support.
              </p>
            ) : (
              <div className="space-y-3">
                <p className="text-sm font-medium">Payment Options:</p>
                {platformMethods.map((method) => (
                  <div
                    key={method.id}
                    className="bg-muted/30 rounded-lg p-3 text-sm space-y-1"
                  >
                    <p className="font-medium">{method.method_name}</p>
                    {Object.entries(method.details).map(([key, value]) =>
                      value ? (
                        <p key={key} className="text-muted-foreground">
                          {key.replace(/_/g, " ")}: <span className="font-mono">{value}</span>
                        </p>
                      ) : null
                    )}
                    {method.instructions && (
                      <p className="text-muted-foreground text-xs mt-1">
                        {method.instructions}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            )}

            <Button
              className="w-full"
              onClick={() => setStep("upload")}
            >
              <Upload className="h-4 w-4 mr-2" />
              I've Made the Payment
            </Button>
          </div>
        )}

        {step === "upload" && createdInvoiceId && (
          <InvoiceProofUpload
            invoiceId={createdInvoiceId}
            currentProofUrl={null}
            onUploadComplete={handleUploadComplete}
          />
        )}

        <DialogFooter>
          {step === "info" && (
            <>
              <Button variant="outline" onClick={() => onOpenChange(false)}>
                Cancel
              </Button>
              <Button onClick={handleProceedToPayment} disabled={loading}>
                {loading && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
                <CreditCard className="h-4 w-4 mr-2" />
                Proceed to Payment
              </Button>
            </>
          )}
          {step === "payment" && (
            <Button variant="outline" onClick={() => setStep("info")}>
              Back
            </Button>
          )}
          {step === "upload" && (
            <Button variant="outline" onClick={() => setStep("payment")}>
              Back
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
